# Generated by Django 3.0 on 2020-05-30 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200529_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientspersonaldetail',
            old_name='mobile_number',
            new_name='mobile',
        ),
        migrations.RemoveField(
            model_name='patientspersonaldetail',
            name='status',
        ),
        migrations.AddField(
            model_name='patientspersonaldetail',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='patientspersonaldetail',
            name='address',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patientspersonaldetail',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='patientspersonaldetail',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
