# Generated by Django 3.0 on 2020-05-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200530_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientspersonaldetail',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
