# Generated by Django 3.0 on 2020-05-30 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0004_patientspersonaldetail_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientspersonaldetail',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patientspersonaldetail',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='patientspersonaldetail',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='patientspersonaldetail',
            name='ptn_id',
        ),
        migrations.AddField(
            model_name='patientspersonaldetail',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
