# Generated by Django 3.0 on 2020-06-01 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_medicines'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Medicines',
            new_name='Medicine',
        ),
    ]
