# Generated by Django 3.0 on 2020-06-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_order_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DoctorName', models.CharField(max_length=100)),
                ('DoctorEmail', models.EmailField(max_length=100)),
                ('DoctorPassword', models.CharField(max_length=20)),
                ('Specialization', models.CharField(max_length=50)),
            ],
        ),
    ]
